language: generic

env:
  - PYTHON_VERSION=3.7
  - PYTHON_VERSION=3.8
os:
  - linux
  - osx

branches:
  only:
    - dev
    - master

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
    fi

  # More conda setup to get miniconda in and a virtual env. setup
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a   # Useful for debugging any issues with conda
  # Create the env
  - conda env create -f environment.yml -n test_env python=$PYTHON_VERSION
  - source activate test_env

install:
  # Install dependencies
  - conda config --add channels usgs-astrogeology
  - conda config --add channels conda-forge
  # Development installation
  - conda install pip setuptools
  - conda install --quiet pytest pytest-cov pytest-qt nbsphinx
  - pip install coveralls travis-sphinx

script:
  - pytest --cov=point_spectra_gui

after_success:
  # Code Coverage
  - coveralls

deploy:
  provider: script
  cleanup: false
  script: bash deploy.sh $PYTHON_VERSION
  on:
    branch: master
