# -*- coding: utf-8 -*-

# Automatically generated - don't edit.
# Use `python setup.py build_ui` to update it.

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formGroupBox = QtWidgets.QGroupBox(Form)
        self.formGroupBox.setObjectName("formGroupBox")
        self.formLayout = QtWidgets.QFormLayout(self.formGroupBox)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.lossLabel = QtWidgets.QLabel(self.formGroupBox)
        self.lossLabel.setObjectName("lossLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lossLabel)
        self.alphaLabel = QtWidgets.QLabel(self.formGroupBox)
        self.alphaLabel.setObjectName("alphaLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.alphaLabel)
        self.numEstLabel = QtWidgets.QLabel(self.formGroupBox)
        self.numEstLabel.setObjectName("numEstLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.numEstLabel)
        self.learningLabel = QtWidgets.QLabel(self.formGroupBox)
        self.learningLabel.setObjectName("learningLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.learningLabel)
        self.subsampleLabel = QtWidgets.QLabel(self.formGroupBox)
        self.subsampleLabel.setObjectName("subsampleLabel")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.subsampleLabel)
        self.min_n_splitLabel = QtWidgets.QLabel(self.formGroupBox)
        self.min_n_splitLabel.setObjectName("min_n_splitLabel")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.min_n_splitLabel)
        self.min_n_leafLabel = QtWidgets.QLabel(self.formGroupBox)
        self.min_n_leafLabel.setObjectName("min_n_leafLabel")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.min_n_leafLabel)
        self.min_fractionLabel = QtWidgets.QLabel(self.formGroupBox)
        self.min_fractionLabel.setObjectName("min_fractionLabel")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.min_fractionLabel)
        self.max_depthLabel = QtWidgets.QLabel(self.formGroupBox)
        self.max_depthLabel.setObjectName("max_depthLabel")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.max_depthLabel)
        self.min_imp_decLabel = QtWidgets.QLabel(self.formGroupBox)
        self.min_imp_decLabel.setObjectName("min_imp_decLabel")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.min_imp_decLabel)
        self.AlphalineEdit = QtWidgets.QLineEdit(self.formGroupBox)
        self.AlphalineEdit.setObjectName("AlphalineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.AlphalineEdit)
        self.numEstlineEdit = QtWidgets.QLineEdit(self.formGroupBox)
        self.numEstlineEdit.setObjectName("numEstlineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.numEstlineEdit)
        self.learninglineEdit = QtWidgets.QLineEdit(self.formGroupBox)
        self.learninglineEdit.setObjectName("learninglineEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.learninglineEdit)
        self.subsamplelineEdit = QtWidgets.QLineEdit(self.formGroupBox)
        self.subsamplelineEdit.setObjectName("subsamplelineEdit")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.subsamplelineEdit)
        self.min_n_splitlineEdit = QtWidgets.QLineEdit(self.formGroupBox)
        self.min_n_splitlineEdit.setObjectName("min_n_splitlineEdit")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.min_n_splitlineEdit)
        self.min_n_leaflineEdit = QtWidgets.QLineEdit(self.formGroupBox)
        self.min_n_leaflineEdit.setObjectName("min_n_leaflineEdit")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.min_n_leaflineEdit)
        self.min_fractionlineEdit = QtWidgets.QLineEdit(self.formGroupBox)
        self.min_fractionlineEdit.setObjectName("min_fractionlineEdit")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.min_fractionlineEdit)
        self.maxdepthlineEdit = QtWidgets.QLineEdit(self.formGroupBox)
        self.maxdepthlineEdit.setObjectName("maxdepthlineEdit")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.maxdepthlineEdit)
        self.min_impuritylineEdit = QtWidgets.QLineEdit(self.formGroupBox)
        self.min_impuritylineEdit.setObjectName("min_impuritylineEdit")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.min_impuritylineEdit)
        self.lossfunclistWidget = QtWidgets.QListWidget(self.formGroupBox)
        self.lossfunclistWidget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.lossfunclistWidget.setObjectName("lossfunclistWidget")
        item = QtWidgets.QListWidgetItem()
        self.lossfunclistWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lossfunclistWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lossfunclistWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lossfunclistWidget.addItem(item)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lossfunclistWidget)
        self.verticalLayout.addWidget(self.formGroupBox)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(("Form"))
        self.formGroupBox.setTitle(("Gradient Boosting Regression"))
        self.lossLabel.setText(("Loss Function"))
        self.alphaLabel.setText(("Alpha"))
        self.numEstLabel.setText(("# of estimators"))
        self.learningLabel.setText(("Learning Rate"))
        self.subsampleLabel.setText(("Subsample"))
        self.min_n_splitLabel.setText(("Minimum # of samples to split"))
        self.min_n_leafLabel.setText(("Minimum # of samples in leaf"))
        self.min_fractionLabel.setText(("Minimum weighted fraction"))
        self.max_depthLabel.setText(("Max Depth"))
        self.min_imp_decLabel.setText(("Minimum impurity decrease"))
        self.AlphalineEdit.setText(("0.9"))
        self.numEstlineEdit.setText(("100"))
        self.learninglineEdit.setText(("0.1"))
        self.subsamplelineEdit.setText(("1.0"))
        self.min_n_splitlineEdit.setText(("2"))
        self.min_n_leaflineEdit.setText(("1"))
        self.min_fractionlineEdit.setText(("0.0"))
        self.maxdepthlineEdit.setText(("3"))
        self.min_impuritylineEdit.setText(("0.0"))
        __sortingEnabled = self.lossfunclistWidget.isSortingEnabled()
        self.lossfunclistWidget.setSortingEnabled(False)
        item = self.lossfunclistWidget.item(0)
        item.setText(("Least Squares"))
        item = self.lossfunclistWidget.item(1)
        item.setText(("Quantile"))
        item = self.lossfunclistWidget.item(2)
        item.setText(("Least Absolute Deviation"))
        item = self.lossfunclistWidget.item(3)
        item.setText(("Huber"))
        self.lossfunclistWidget.setSortingEnabled(__sortingEnabled)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

